package dev.mixinmcp.resolve

import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.FieldVisitor
import org.objectweb.asm.Handle
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import org.objectweb.asm.util.Textifier
import org.objectweb.asm.util.TraceMethodVisitor
import java.io.PrintWriter
import java.io.StringWriter

/**
 * ASM-based bytecode analysis. Identifies synthetic methods, lambdas,
 * and parses lambda source method names for mixin target resolution.
 */
object BytecodeAnalyzer {

    /**
     * Category of an outgoing call discovered in a method body.
     *
     * - METHOD — regular method invocation: `INVOKEVIRTUAL/STATIC/SPECIAL/INTERFACE`,
     *   or an `INVOKEDYNAMIC` whose resolved impl handle points to a non-synthetic
     *   method (i.e. a method reference to a real method, e.g. `this::setPosToBed`).
     *   Source-side equivalents are direct calls and `Foo::bar` method references.
     * - CONSTRUCTOR — `INVOKESPECIAL` of `<init>`, or an `INVOKEDYNAMIC` impl that
     *   points at `<init>`. Source-side equivalents are `new Foo(...)` and `Foo::new`.
     * - LAMBDA — the impl handle behind an `INVOKEDYNAMIC` that resolves to a real
     *   synthetic `lambda$X$N` method generated by the compiler. This is the target
     *   a mixin author would pick up when injecting into a lambda body.
     */
    enum class CalleeKind { METHOD, CONSTRUCTOR, LAMBDA }

    data class CalleeRef(
        val owner: String,       // canonical: "com.foo.Bar" (with '.' separators, '$' for nested)
        val name: String,        // method name, "<init>" for ctors, "lambda$x$0" etc. for lambdas
        val descriptor: String,  // JVM method descriptor, e.g. "(I)V"
        val kind: CalleeKind,
    )

    data class MethodInfo(
        val access: Int,
        val name: String,
        val descriptor: String,
        val signature: String?,
        var instructions: String? = null,
    ) {
        val isSynthetic: Boolean get() = access and Opcodes.ACC_SYNTHETIC != 0
        val isBridge: Boolean get() = access and Opcodes.ACC_BRIDGE != 0
        val isLambda: Boolean get() = isSynthetic && name.startsWith("lambda$")

        /**
         * For synthetic lambdas like "lambda$tick$0", extracts the source method name.
         */
        val lambdaSourceMethod: String?
            get() {
                if (!isLambda) return null
                val stripped: String = name.removePrefix("lambda$")
                val dollarIndex: Int = stripped.lastIndexOf('$')
                return if (dollarIndex > 0) stripped.substring(0, dollarIndex) else stripped
            }
    }

    data class FieldInfo(
        val access: Int,
        val name: String,
        val descriptor: String,
        val value: Any?,
    ) {
        val isSynthetic: Boolean get() = access and Opcodes.ACC_SYNTHETIC != 0
    }

    data class ClassAnalysis(
        val version: Int,
        val access: Int,
        val name: String,
        val superName: String?,
        val interfaces: List<String>,
        val methods: List<MethodInfo>,
        val fields: List<FieldInfo>,
    )

    /**
     * Performs full class analysis. Set includeInstructions=true to also
     * capture bytecode instructions for each method (expensive).
     */
    fun analyze(classBytes: ByteArray, includeInstructions: Boolean = false): ClassAnalysis {
        val reader = ClassReader(classBytes)
        val methods = mutableListOf<MethodInfo>()
        val fields = mutableListOf<FieldInfo>()

        reader.accept(
            object : ClassVisitor(Opcodes.ASM9) {
                override fun visitMethod(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    exceptions: Array<out String>?,
                ): MethodVisitor? {
                    val info = MethodInfo(access, name, descriptor, signature)
                    methods.add(info)

                    if (includeInstructions) {
                        val sw = StringWriter()
                        val printer = Textifier()
                        val tmv = TraceMethodVisitor(printer)
                        return object : MethodVisitor(Opcodes.ASM9, tmv) {
                            override fun visitEnd() {
                                super.visitEnd()
                                printer.print(PrintWriter(sw))
                                info.instructions = sw.toString().trimEnd()
                            }
                        }
                    }
                    return null
                }

                override fun visitField(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    value: Any?,
                ): FieldVisitor? {
                    fields.add(FieldInfo(access, name, descriptor, value))
                    return null
                }
            },
            if (includeInstructions) 0 else ClassReader.SKIP_CODE,
        )

        return ClassAnalysis(
            version = reader.readUnsignedShort(6),
            access = reader.access,
            name = reader.className.replace('/', '.'),
            superName = reader.superName?.replace('/', '.'),
            interfaces = reader.interfaces?.map { it.replace('/', '.') } ?: emptyList(),
            methods = methods,
            fields = fields,
        )
    }

    /**
     * Gets the textified bytecode for a single method in a class.
     * Returns javap-style output for just that method.
     */
    fun analyzeMethod(
        classBytes: ByteArray,
        targetMethodName: String,
        targetDescriptor: String? = null,
    ): String? {
        val reader = ClassReader(classBytes)
        val sw = StringWriter()
        var found = false

        reader.accept(
            object : ClassVisitor(Opcodes.ASM9) {
                override fun visitMethod(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    exceptions: Array<out String>?,
                ): MethodVisitor? {
                    if (name == targetMethodName &&
                        (targetDescriptor == null || descriptor == targetDescriptor)
                    ) {
                        found = true
                        val printer = Textifier()
                        return object : MethodVisitor(Opcodes.ASM9, TraceMethodVisitor(printer)) {
                            override fun visitEnd() {
                                super.visitEnd()
                                val pw = PrintWriter(sw)
                                pw.println("  // access: ${accessFlagsToString(access)}")
                                pw.println("  // descriptor: $descriptor")
                                if (signature != null) pw.println("  // signature: $signature")
                                pw.println()
                                printer.print(pw)
                                pw.flush()
                            }
                        }
                    }
                    return null
                }
            },
            0,
        )

        return if (found) sw.toString().trimEnd() else null
    }

    /**
     * Extracts outgoing calls from a single method's body as structured
     * [CalleeRef]s. Covers INVOKEVIRTUAL/STATIC/SPECIAL/INTERFACE and resolves
     * INVOKEDYNAMIC whose bootstrap method is `LambdaMetafactory.metafactory`
     * or `altMetafactory` to the impl handle (the real synthetic target —
     * `lambda$...` or a directly-referenced method for `Foo::bar`).
     *
     * Non-lambda INVOKEDYNAMICs (string concat, switch bootstrap, etc.) are
     * intentionally omitted: they don't represent user-meaningful call
     * targets for mixin authoring.
     *
     * @return null if no method with the given name/descriptor was found in
     *   the class, or an empty list for abstract / native methods with no
     *   code. Caller order is preserved, with duplicates still present —
     *   deduplication is up to the consumer.
     */
    fun extractCallees(
        classBytes: ByteArray,
        targetMethodName: String,
        targetDescriptor: String? = null,
    ): List<CalleeRef>? {
        val reader = ClassReader(classBytes)
        val callees = mutableListOf<CalleeRef>()
        var methodFound = false
        var methodHasCode = false

        reader.accept(
            object : ClassVisitor(Opcodes.ASM9) {
                override fun visitMethod(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    exceptions: Array<out String>?,
                ): MethodVisitor? {
                    if (name != targetMethodName) return null
                    if (targetDescriptor != null && descriptor != targetDescriptor) return null
                    methodFound = true
                    val abstractOrNative: Boolean =
                        access and (Opcodes.ACC_ABSTRACT or Opcodes.ACC_NATIVE) != 0
                    if (abstractOrNative) return null
                    methodHasCode = true
                    return object : MethodVisitor(Opcodes.ASM9) {
                        override fun visitMethodInsn(
                            opcode: Int,
                            owner: String,
                            name: String,
                            descriptor: String,
                            isInterface: Boolean,
                        ) {
                            val kind: CalleeKind = when {
                                opcode == Opcodes.INVOKESPECIAL && name == "<init>" -> CalleeKind.CONSTRUCTOR
                                else -> CalleeKind.METHOD
                            }
                            callees.add(
                                CalleeRef(
                                    owner = owner.replace('/', '.'),
                                    name = name,
                                    descriptor = descriptor,
                                    kind = kind,
                                ),
                            )
                        }

                        override fun visitInvokeDynamicInsn(
                            name: String,
                            descriptor: String,
                            bootstrapMethodHandle: Handle,
                            vararg bootstrapMethodArguments: Any?,
                        ) {
                            if (!isLambdaMetafactory(bootstrapMethodHandle)) return
                            val impl: Handle = bootstrapMethodArguments.getOrNull(1) as? Handle ?: return
                            val kind: CalleeKind = when {
                                impl.name == "<init>" -> CalleeKind.CONSTRUCTOR
                                impl.name.startsWith("lambda$") -> CalleeKind.LAMBDA
                                else -> CalleeKind.METHOD
                            }
                            callees.add(
                                CalleeRef(
                                    owner = impl.owner.replace('/', '.'),
                                    name = impl.name,
                                    descriptor = impl.desc,
                                    kind = kind,
                                ),
                            )
                        }
                    }
                }
            },
            ClassReader.SKIP_DEBUG or ClassReader.SKIP_FRAMES,
        )

        if (!methodFound) return null
        if (!methodHasCode) return emptyList()
        return callees
    }

    private fun isLambdaMetafactory(handle: Handle): Boolean {
        if (handle.owner != "java/lang/invoke/LambdaMetafactory") return false
        return handle.name == "metafactory" || handle.name == "altMetafactory"
    }

    private val ACCESS_FLAGS: List<Pair<Int, String>> = listOf(
        Opcodes.ACC_PUBLIC to "public",
        Opcodes.ACC_PRIVATE to "private",
        Opcodes.ACC_PROTECTED to "protected",
        Opcodes.ACC_STATIC to "static",
        Opcodes.ACC_FINAL to "final",
        Opcodes.ACC_SYNCHRONIZED to "synchronized",
        Opcodes.ACC_VOLATILE to "volatile",
        Opcodes.ACC_TRANSIENT to "transient",
        Opcodes.ACC_NATIVE to "native",
        Opcodes.ACC_ABSTRACT to "abstract",
        Opcodes.ACC_SYNTHETIC to "synthetic",
        Opcodes.ACC_BRIDGE to "bridge",
    )

    fun accessFlagsToString(access: Int): String =
        ACCESS_FLAGS
            .filter { (flag, _) -> access and flag != 0 }
            .map { it.second }
            .joinToString(" ")
}
